# This is a basic workflow to help you get started with Actions

name: syslinux
on:
  push:
    tags:
      - '*'
    release:
      types: [published]

jobs:
  build:
    name: syslinux
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: setup install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install perl uuid-dev nasm git mingw-w64 make gcc python libc6-dev-i386
          df -h

      - name: make files
        run: |
          make
          make bios
          make bios efi64 installer
          mkdir syslinux-efi
          make O=./syslinux-efi efi64
          mkdir syslinux-bios
          make O=./syslinux-bios bios
          ls -l ./syslinux-efi
          ls -l ./syslinux-bios

  
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
#      - name: Upload Release Asset
#        id: upload-release-asset 
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: ./bin/targets/ar71xx/generic/
#          asset_name: ./bin/targets/ar71xx/generic/openwrt-ar71xx-generic-dragino2-squashfs-sysupgrade.bin
#          asset_content_type: application/bin
          
